apiVersion: apps/v1
kind: Deployment
metadata:
  name: msdevshow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msdevshow
  template:
    metadata:
      labels:
        app: msdevshow
    spec:
      containers:
        - name: msdevshow-container
          image: ytechie/msdevshow
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: msdevshow-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: msdevshow
